POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "root",
    "name": "root",
    "password": "123456"
}

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "hellas",
    "name": "Arto Hellas",
    "password": "123456"
}

###
POST http://localhost:3003/api/users
Content-Type: application/json

{
    "username": "mluukkai",
    "name": "Matti Luukkainen",
    "password": "123456"
}
